#
# package     Extly.Container
# subpackage  Lando Boilerplate - https://github.com/anibalsanchez/lando-lamp-boilerplate
#
# author      Extly, CB.
# copyright   Copyright (C) 2012-2025 Extly, CB <team@extly.com>
# license     MIT
# link        https://extly.com
#
# WORKING WITH DRUPAL https://docs.lando.dev/plugins/drupal/index.html

# REQUIREMENTS: Lando 3

name: <NEW-CONTAINER-NAME>
recipe: drupal11

proxy:
  appserver:
    - <NEW-CONTAINER-NAME>.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: "8.4"
  via: apache
  webroot: www
  xdebug: true
  config:
    php: config/php.ini

# Disable key loading - https://docs.lando.dev/config/ssh.html#customizing
keys: false

services:
  appserver:
    ports:
      # A nice handy known-local port  http://localhost:8080
      - "8080:80"

    # Bind my exposes services to all intefaces
    #  - "0.0.0.0::80"

    build_as_root:
      # Apache mod headers
      - a2enmod headers

      # Install xdebug-2.9.8, wait until Xdebug 3 is fully tested
      # - pecl uninstall xdebug
      # - pecl install xdebug-2.9.8

    # ADDING OR REMOVING EXTENSIONS - https://docs.devwithlando.io/tutorials/php.html#adding-or-removing-extensions
    # build_as_root:
    #   - apt-get update -y
    #   - apt-get install -y libxml2-dev libxslt-dev
    #   - docker-php-ext-install dom xmlrpc xsl

  database:
    type: mysql
    # type: mysql:5.7
    # type: mysql:8.0
    portforward: 3306
    creds:
      user: <NEW-CONTAINER-NAME>db
      password: <NEW-CONTAINER-NAME>db
      database: <NEW-CONTAINER-NAME>db

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    portforward: 1025
    hogfrom:
      - appserver

  # node:
  #   type: node
  #   globals:
  #     gulp-cli: latest

tooling:
  # Tooling Example
  # https://github.com/lando/lando/tree/master/examples/tooling
  # USING SCRIPTY THINGS
  # https://docs.devwithlando.io/config/services.html#using-scripty-things
  # npm:
  #   service: node
  # node:
  #   service: node
  # gulp:
  #   service: node
  # yarn:
  #   service: node
