#
# package     Extly.Container
# subpackage  Lando Boilerplate - https://github.com/anibalsanchez/lando-lamp-boilerplate
#
# author      Extly, CB.
# copyright   Copyright (C) 2012-2025 Extly, CB <team@extly.com>
# license     MIT
# link        https://extly.com
#
# WORKING WITH LAMP - https://docs.lando.dev/plugins/lamp/index.html
#
# REQUIREMENTS: Lando 3

name: <NEW-CONTAINER-NAME>
recipe: lamp

proxy:
  appserver:
    - <NEW-CONTAINER-NAME>.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: "8.4"
  via: apache
  webroot: www
  xdebug: true
  config:
    php: config/php.ini

services:
  appserver:
    ports:
      # A nice handy known-local port  http://localhost:8080
      - "8080:80"

    # Bind my exposes services to all intefaces
    #  - "0.0.0.0::80"

    build_as_root:
      # Apache mod headers
      - a2enmod headers

      # Install xdebug-2.9.8, wait until Xdebug 3 is fully tested
      # - pecl uninstall xdebug
      # - pecl install xdebug-2.9.8

  database:
    type: mysql
    # type: mysql:5.7
    # type: mysql:8.0
    portforward: 3306
    creds:
      user: <NEW-CONTAINER-NAME>db
      password: <NEW-CONTAINER-NAME>db
      database: <NEW-CONTAINER-NAME>db

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    hogfrom:
      - appserver
